Problem: `AttributeError` on `applicationversion` admin
`AttributeError: 'ApplicationVersionMembership' object has no attribute 'application_version'`

Solution: Use `image_version` instead of `application_version`