Allocation Sources for Jetstream (#182)
* Revert "Update secrets template" (#175)

This reverts commit 3b3bdef1e7a32bb27f98023deecd74508e6746eb.

* Incremented version for django-iplant-auth

0.1.15 includes a `uid` function that is needed by a Celery task.

This commit resolved the following Traceback:

Traceback (most recent call last):
  File "/opt/dev/atmosphere/service/networking.py", line 135, in get_or_create_user_subnet
      cidr = get_cidr(username, inc, get_unique_number)
  File "/opt/dev/atmosphere/service/networking.py", line 81, in get_default_subnet
      uid_number = get_uid_number(username)
  File "/opt/dev/atmosphere/service/networking.py", line 32, in _get_unique_id
      from iplantauth.protocol.ldap import _get_uid_number
ImportError: cannot import name _get_uid_number

* Rename 'logging' to make it easier to use python `logging`

* Updates to include missing files

* Fix allocation to allow 'start_date' and 'end_date' when looking for specific point in time

* Allow a 'hook' to determine if user is valid *before* creating accounts for them.

* [WIP] Include latest TACC endpoint

* Can move from XUP->TACC usernmaes
* Pass start_date and end_date to get specific allocation windows

* Refactor code to keep API calls in jetstream/api.py

* Update jetstream models and unicode

* Typo fixed from prior rebase-merge

* Fix merge during rebase

* Add a basic admin page to Django

* Update installed_apps (for now)

* Move 'user validation' code to a plugin directory

* Cleanup code related to new_account creation and validation

* Cleanup code related to creation of an Identity

* Add some additional code to make testing allocation via script easier

* Add a script to call for allocation result externally

* Make the external allocation script more closely resemble the 'other' allocation method (active-only)

* Hotfix to allow this to work on non-jetstream server

* report creation logic added

* indentation fixed for the file

* Add steves commit on top of amits working branch. Verified that fill_user_allocations() works as expected, could be used in a celery task.

* Added new models+migrations+signals for updating the tables + API endpoint for AllocationSource (WIP -- Still returning null in some places)

* API Scaffolding

- Event Serializer/view and validation
- Added new attribute for instances: allocation_source
- Updated the AllocationSource serializer

	modified:   api/v2/serializers/details/__init__.py
	modified:   api/v2/serializers/details/allocation_source.py
	new file:   api/v2/serializers/details/event.py
	modified:   api/v2/serializers/details/instance.py
	modified:   api/v2/urls.py
	modified:   api/v2/views/__init__.py
	new file:   api/v2/views/event.py

* Added v2 instance POST serialization for allocation_source_id (v1 Coming Soon), included new migration for 'filter_id' for the engines username sorting

* report logic updated to handle username filters and return allocation source based computer per user. Also updated report logic to handle new allocation source tables

* Update API endpoints to change_allocation_source. Works on v1 and v2 endpoints.

* agg_id changed to filter_id in allocation_logic script

* PEP8 + fix 500 error on EventSerializer

* Comment out 'debugging circuit-breakers' and signal for updating the user allocation sources

* Include 'url' in fields to avoid 500 from the Serializer

* Fix vars

* Fixes along the way

* minor text fixes

* Make 'allocation_source_id' a requirement for POST. Handle the Airport edge case later...

* EventTable object creation and report creation wrapped up in celery tasks. Burn rate calculation logic added. Allocation calculation script modified to adapt new events and instance allocation source change

* delete allocation_logic.py from root dir and move to service/

* fixed error with settings.py. Fixed nonetype error in a condition in allocation_logic.py

* fixed

* Code cleanup + various bugfixes

Changes made:
- AllocationSource.id was being used in hooks, rather than
AllocationSource.source_id
- The string 'Still Running' was being used for running instances,
causing errors in datetime comparison.
- Tabs instead of 4-spaces and other PEP8 things
	modified:   core/hooks/allocation_source.py
	modified:   core/models/user.py
	modified:   jetstream/tasks.py
	modified:   service/allocation_logic.py

* API should return all  values in hours, not seconds

* Return time in Hrs not Sec

* Event payload includes 'source_id' not 'id'

* Not in seconds anymore. Returns hours.

* Leave this print statement for any who need to debug :)

* Attempt to send any unsuccessful TAS reports after creation.

* total_usage paramters changed and end_date and allocation_source name is not required now. total_usage shifted to core.models.allocation_source

* Cleanup Jetstream API calls into a single TASAPIDriver class. Use sensible defaults as suggested by Jetstream.

* identation improved for this file

* feature flagging loosely handled

* Cleanup settings to use Jetstream-specific code only when USE_JETSTREAM_PLUGIN and USE_ALLOCATION_SOURCE is true.

* Code cleanup

* This task will now complete all necessary 'bootstrapping' associations.

* Add new variables to the .dist file

* Fix migrations (DevNote: BREAKING CHANGE -- DB re-build required)

* Cleanup & replace remaining 'filter_id','agg_id' for 'entity_id'

* Fixes after review - pt1

* Reporting :100:

* Rename 'create_report' task

* Fixes after review - pt2

* PEP8 on service/allocation_logic.py -- REVIEW NEEDED --

* Validate the entity_id, include 'username' in the payload of 'instance_allocation_source_changed' event

* logic added to fetch current allocation source from eventtable

* filtered events are now ordered by timestamp

* Add email early warning system -- For all users on an allocation, Current hard-coded Threshold Values: 10, 25, 50, 75, 90

* Add related_name for easy query and avoiding 'verylongnamed_set' notation

* Minor bug fixes

* Consolidated JETSTREAM_PLUGIN into USE_JETSTREAM_PLUGIN variable (#184)