Problem: Celery sometimes reports 'Too many open files'
```
OSError: [Errno 24] Too many open files
```

Solution: Set the `CELERYD_ULIMIT` variable in `celeryd.default` to a
higher number

TODO: Still not sure why this is suddenly causing a problem. Is it
something to do with the new version of Celery we're using?