Problem: Modifying immutable request dictionary
Tests failed with:

```
AttributeError: This QueryDict instance is immutable
```

I think the new version of DRF has immutable request data dictionaries.

Solution: Create `action_params` as a mutable copy of `request.data`
instead of directly modifying `request.data`