Problem: Typo in global burn rate attribute
Tests failed with:

```
FieldError: Invalid field name(s) for model AllocationSourceSnapshot: 'burn_rate'.
```

Global burn rate was never correctly set, because the attribute used in
the `update_or_create` method was `burn_rate` instead of
`global_burn_rate`. We never figured out why, until the upgrade to
Django which started checking for these things, and then failed the
tests.

Solution: Change `burn_rate` to `global_burn_rate`